
/*
Auto-generated by CVXPYgen on April 04, 2026 at 21:53:04.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_w_tr(0.00000000000000000000);
  cpg_update_f_ct_last(0.75617980916332316887);
  cpg_update_A_ct_last(0, -1.77341254255106850479);
  cpg_update_B_ct_last(0, 0.51617103117450546801);
  cpg_update_C_ct_last(0, 0.44826026020084863699);
  cpg_update_S_ct_last(0, -0.82918654895572030394);
  cpg_update_f_comp_last(0.81463688894322161538);
  cpg_update_gf_comp_last(0, 1.46243606343544074733);
  cpg_update_f_dt_last(0, 0.89397512775180998368);
  cpg_update_gf_dt_last(0, 0.32516737283191904373);
  cpg_update_X_last(0, 0.10278092826010004623);
  cpg_update_f_bar(0, 0.07663661313635648786);
  cpg_update_A_bar(0, 1.42856970322058507428);
  cpg_update_B_bar(0, -1.70318242044424916770);
  cpg_update_C_bar(0, -0.16116719953756608597);
  cpg_update_S_bar(0, 1.45116699992383968443);
  cpg_update_U_last(0, 0.28017738818406717760);
  cpg_update_S_last(0, 0.68594127135395521755);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<768; i++) {
    printf("dx[%d] = %f\n", i, CPG_Result.prim->dx[i]);
  }
  for(i=0; i<128; i++) {
    printf("du[%d] = %f\n", i, CPG_Result.prim->du[i]);
  }
  for(i=0; i<31; i++) {
    printf("ds[%d] = %f\n", i, CPG_Result.prim->ds[i]);
  }
  for(i=0; i<744; i++) {
    printf("nu[%d] = %f\n", i, CPG_Result.prim->nu[i]);
  }
  for(i=0; i<31; i++) {
    printf("S[%d] = %f\n", i, CPG_Result.prim->S[i]);
  }
  for(i=0; i<768; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<128; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }

  // Print dual solution
  for(i=0; i<24; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<24; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<24; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<24; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<24; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<24; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<24; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<24; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<24; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<24; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<24; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<24; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<24; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<24; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<24; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<24; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<24; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<24; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<24; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<24; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  for(i=0; i<24; i++) {
    printf("d20[%d] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  for(i=0; i<24; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  for(i=0; i<24; i++) {
    printf("d22[%d] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  for(i=0; i<24; i++) {
    printf("d23[%d] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<24; i++) {
    printf("d24[%d] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  for(i=0; i<24; i++) {
    printf("d25[%d] = %f\n", i, CPG_Result.dual->d25[i]);
  }
  for(i=0; i<24; i++) {
    printf("d26[%d] = %f\n", i, CPG_Result.dual->d26[i]);
  }
  for(i=0; i<24; i++) {
    printf("d27[%d] = %f\n", i, CPG_Result.dual->d27[i]);
  }
  for(i=0; i<24; i++) {
    printf("d28[%d] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  for(i=0; i<24; i++) {
    printf("d29[%d] = %f\n", i, CPG_Result.dual->d29[i]);
  }
  for(i=0; i<24; i++) {
    printf("d30[%d] = %f\n", i, CPG_Result.dual->d30[i]);
  }
  for(i=0; i<768; i++) {
    printf("d31[%d] = %f\n", i, CPG_Result.dual->d31[i]);
  }
  for(i=0; i<128; i++) {
    printf("d32[%d] = %f\n", i, CPG_Result.dual->d32[i]);
  }
  for(i=0; i<31; i++) {
    printf("d33[%d] = %f\n", i, CPG_Result.dual->d33[i]);
  }
  for(i=0; i<31; i++) {
    printf("d34[%d] = %f\n", i, CPG_Result.dual->d34[i]);
  }
  printf("d35 = %f\n", CPG_Result.dual->d35);
  for(i=0; i<31; i++) {
    printf("d36[%d] = %f\n", i, CPG_Result.dual->d36[i]);
  }
  for(i=0; i<8; i++) {
    printf("d37[%d] = %f\n", i, CPG_Result.dual->d37[i]);
  }
  for(i=0; i<5; i++) {
    printf("d38[%d] = %f\n", i, CPG_Result.dual->d38[i]);
  }
  for(i=0; i<3; i++) {
    printf("d39[%d] = %f\n", i, CPG_Result.dual->d39[i]);
  }
  for(i=0; i<3; i++) {
    printf("d40[%d] = %f\n", i, CPG_Result.dual->d40[i]);
  }
  printf("d41 = %f\n", CPG_Result.dual->d41);
  printf("d42 = %f\n", CPG_Result.dual->d42);
  printf("d43 = %f\n", CPG_Result.dual->d43);
  printf("d44 = %f\n", CPG_Result.dual->d44);
  printf("d45 = %f\n", CPG_Result.dual->d45);
  printf("d46 = %f\n", CPG_Result.dual->d46);
  printf("d47 = %f\n", CPG_Result.dual->d47);
  printf("d48 = %f\n", CPG_Result.dual->d48);
  printf("d49 = %f\n", CPG_Result.dual->d49);
  printf("d50 = %f\n", CPG_Result.dual->d50);
  printf("d51 = %f\n", CPG_Result.dual->d51);
  printf("d52 = %f\n", CPG_Result.dual->d52);
  printf("d53 = %f\n", CPG_Result.dual->d53);
  for(i=0; i<4; i++) {
    printf("d54[%d] = %f\n", i, CPG_Result.dual->d54[i]);
  }
  for(i=0; i<4; i++) {
    printf("d55[%d] = %f\n", i, CPG_Result.dual->d55[i]);
  }
  for(i=0; i<32; i++) {
    printf("d56[%d] = %f\n", i, CPG_Result.dual->d56[i]);
  }
  for(i=0; i<32; i++) {
    printf("d57[%d] = %f\n", i, CPG_Result.dual->d57[i]);
  }
  for(i=0; i<96; i++) {
    printf("d58[%d] = %f\n", i, CPG_Result.dual->d58[i]);
  }

  return 0;

}
