
/*
Auto-generated by CVXPYgen on April 04, 2026 at 21:53:04.
Content: Type definitions and variable declarations.
*/

#include "qoco.h"

#ifndef CPG_TYPES_H
# define CPG_TYPES_H

typedef QOCOFloat cpg_float;
typedef QOCOInt cpg_int;

// Compressed sparse column matrix
typedef struct {
  cpg_int      *p;
  cpg_int      *i;
  cpg_float    *x;
  cpg_int      nnz;
} cpg_csc;

// Canonical parameters
typedef struct {
  cpg_csc      *P;         // Canonical parameter P
  cpg_float    *c;         // Canonical parameter c
  cpg_float    d;          // Canonical parameter d
  cpg_csc      *A;         // Canonical parameter A
  cpg_float    *b;         // Canonical parameter b
  cpg_csc      *G;         // Canonical parameter G
  cpg_float    *h;         // Canonical parameter h
} Canon_Params_t;

// Flags indicating outdated canonical parameters
typedef struct {
  int        P;            // Bool, if canonical parameter P outdated
  int        c;            // Bool, if canonical parameter c outdated
  int        d;            // Bool, if canonical parameter d outdated
  int        A;            // Bool, if canonical parameter A outdated
  int        b;            // Bool, if canonical parameter b outdated
  int        G;            // Bool, if canonical parameter G outdated
  int        h;            // Bool, if canonical parameter h outdated
} Canon_Outdated_t;

// Primal solution
typedef struct {
  cpg_float    *dx;        // Your variable dx
  cpg_float    *du;        // Your variable du
  cpg_float    *ds;        // Your variable ds
  cpg_float    *nu;        // Your variable nu
  cpg_float    *S;         // Your variable S
  cpg_float    *X;         // Your variable X
  cpg_float    *U;         // Your variable U
} CPG_Prim_t;

// Dual solution
typedef struct {
  cpg_float    *d0;        // Your dual variable for constraint d0
  cpg_float    *d1;        // Your dual variable for constraint d1
  cpg_float    *d2;        // Your dual variable for constraint d2
  cpg_float    *d3;        // Your dual variable for constraint d3
  cpg_float    *d4;        // Your dual variable for constraint d4
  cpg_float    *d5;        // Your dual variable for constraint d5
  cpg_float    *d6;        // Your dual variable for constraint d6
  cpg_float    *d7;        // Your dual variable for constraint d7
  cpg_float    *d8;        // Your dual variable for constraint d8
  cpg_float    *d9;        // Your dual variable for constraint d9
  cpg_float    *d10;       // Your dual variable for constraint d10
  cpg_float    *d11;       // Your dual variable for constraint d11
  cpg_float    *d12;       // Your dual variable for constraint d12
  cpg_float    *d13;       // Your dual variable for constraint d13
  cpg_float    *d14;       // Your dual variable for constraint d14
  cpg_float    *d15;       // Your dual variable for constraint d15
  cpg_float    *d16;       // Your dual variable for constraint d16
  cpg_float    *d17;       // Your dual variable for constraint d17
  cpg_float    *d18;       // Your dual variable for constraint d18
  cpg_float    *d19;       // Your dual variable for constraint d19
  cpg_float    *d20;       // Your dual variable for constraint d20
  cpg_float    *d21;       // Your dual variable for constraint d21
  cpg_float    *d22;       // Your dual variable for constraint d22
  cpg_float    *d23;       // Your dual variable for constraint d23
  cpg_float    *d24;       // Your dual variable for constraint d24
  cpg_float    *d25;       // Your dual variable for constraint d25
  cpg_float    *d26;       // Your dual variable for constraint d26
  cpg_float    *d27;       // Your dual variable for constraint d27
  cpg_float    *d28;       // Your dual variable for constraint d28
  cpg_float    *d29;       // Your dual variable for constraint d29
  cpg_float    *d30;       // Your dual variable for constraint d30
  cpg_float    *d31;       // Your dual variable for constraint d31
  cpg_float    *d32;       // Your dual variable for constraint d32
  cpg_float    *d33;       // Your dual variable for constraint d33
  cpg_float    *d34;       // Your dual variable for constraint d34
  cpg_float    d35;        // Your dual variable for constraint d35
  cpg_float    *d36;       // Your dual variable for constraint d36
  cpg_float    *d37;       // Your dual variable for constraint d37
  cpg_float    *d38;       // Your dual variable for constraint d38
  cpg_float    *d39;       // Your dual variable for constraint d39
  cpg_float    *d40;       // Your dual variable for constraint d40
  cpg_float    d41;        // Your dual variable for constraint d41
  cpg_float    d42;        // Your dual variable for constraint d42
  cpg_float    d43;        // Your dual variable for constraint d43
  cpg_float    d44;        // Your dual variable for constraint d44
  cpg_float    d45;        // Your dual variable for constraint d45
  cpg_float    d46;        // Your dual variable for constraint d46
  cpg_float    d47;        // Your dual variable for constraint d47
  cpg_float    d48;        // Your dual variable for constraint d48
  cpg_float    d49;        // Your dual variable for constraint d49
  cpg_float    d50;        // Your dual variable for constraint d50
  cpg_float    d51;        // Your dual variable for constraint d51
  cpg_float    d52;        // Your dual variable for constraint d52
  cpg_float    d53;        // Your dual variable for constraint d53
  cpg_float    *d54;       // Your dual variable for constraint d54
  cpg_float    *d55;       // Your dual variable for constraint d55
  cpg_float    *d56;       // Your dual variable for constraint d56
  cpg_float    *d57;       // Your dual variable for constraint d57
  cpg_float    *d58;       // Your dual variable for constraint d58
} CPG_Dual_t;

// Solver information
typedef struct {
  cpg_float    obj_val;    // Objective function value
  cpg_int      iter;       // Number of iterations
  cpg_int      status;     // Solver status
  cpg_float    pri_res;    // Primal residual
  cpg_float    dua_res;    // Dual residual
} CPG_Info_t;

// Solution and solver information
typedef struct {
  CPG_Prim_t *prim;        // Primal solution
  CPG_Dual_t *dual;        // Dual solution
  CPG_Info_t *info;        // Solver info
} CPG_Result_t;

// Parameter deltas
typedef struct {
  cpg_float    *w_tr;      // Delta of your parameter w_tr
  cpg_float    *f_ct_last;   // Delta of your parameter f_ct_last
  cpg_float    *A_ct_last;   // Delta of your parameter A_ct_last
  cpg_float    *B_ct_last;   // Delta of your parameter B_ct_last
  cpg_float    *C_ct_last;   // Delta of your parameter C_ct_last
  cpg_float    *S_ct_last;   // Delta of your parameter S_ct_last
  cpg_float    *f_comp_last;   // Delta of your parameter f_comp_last
  cpg_float    *gf_comp_last;   // Delta of your parameter gf_comp_last
  cpg_float    *f_dt_last;   // Delta of your parameter f_dt_last
  cpg_float    *gf_dt_last;   // Delta of your parameter gf_dt_last
  cpg_float    *X_last;    // Delta of your parameter X_last
  cpg_float    *f_bar;     // Delta of your parameter f_bar
  cpg_float    *A_bar;     // Delta of your parameter A_bar
  cpg_float    *B_bar;     // Delta of your parameter B_bar
  cpg_float    *C_bar;     // Delta of your parameter C_bar
  cpg_float    *S_bar;     // Delta of your parameter S_bar
  cpg_float    *U_last;    // Delta of your parameter U_last
  cpg_float    *S_last;    // Delta of your parameter S_last
} CPG_Delta_t;

// Solver settings
typedef struct {
  cpg_int    max_iters;
  cpg_int    bisect_iters;
  cpg_int    ruiz_iters;
  cpg_int    iter_ref_iters;
  cpg_float  kkt_static_reg;
  cpg_float  kkt_dynamic_reg;
  cpg_float  abstol;
  cpg_float  reltol;
  cpg_float  abstol_inacc;
  cpg_float  reltol_inacc;
  cpg_int    verbose;
} Canon_Settings_t;

#endif // ifndef CPG_TYPES_H

// Vector containing flattened user-defined parameters
extern cpg_float cpg_params_vec[34170];

// Sparse mappings from user-defined to canonical parameters
extern cpg_csc canon_P_map;
extern cpg_csc canon_c_map;
extern cpg_csc canon_d_map;
extern cpg_csc canon_A_map;
extern cpg_csc canon_b_map;
extern cpg_csc canon_G_map;
extern cpg_csc canon_h_map;

// Canonical parameters
extern cpg_csc canon_P;
extern cpg_csc canon_P_conditioning;
extern cpg_float canon_c[3542];
extern cpg_float canon_c_conditioning[3542];
extern cpg_csc canon_A;
extern cpg_csc canon_A_conditioning;
extern cpg_float canon_b[1710];
extern cpg_float canon_b_conditioning[1710];
extern cpg_csc canon_G;
extern cpg_csc canon_G_conditioning;
extern cpg_float canon_h[3005];
extern cpg_float canon_h_conditioning[3005];

// Struct containing canonical parameters
extern Canon_Params_t Canon_Params;
extern Canon_Params_t Canon_Params_conditioning;

// Struct containing flags for outdated canonical parameters
extern Canon_Outdated_t Canon_Outdated;

// User-defined variables
extern cpg_float cpg_dx[768];
extern cpg_float cpg_du[128];
extern cpg_float cpg_ds[31];
extern cpg_float cpg_nu[744];
extern cpg_float cpg_S[31];
extern cpg_float cpg_X[768];
extern cpg_float cpg_U[128];

// Dual variables associated with user-defined constraints
extern cpg_float cpg_d0[24];
extern cpg_float cpg_d1[24];
extern cpg_float cpg_d2[24];
extern cpg_float cpg_d3[24];
extern cpg_float cpg_d4[24];
extern cpg_float cpg_d5[24];
extern cpg_float cpg_d6[24];
extern cpg_float cpg_d7[24];
extern cpg_float cpg_d8[24];
extern cpg_float cpg_d9[24];
extern cpg_float cpg_d10[24];
extern cpg_float cpg_d11[24];
extern cpg_float cpg_d12[24];
extern cpg_float cpg_d13[24];
extern cpg_float cpg_d14[24];
extern cpg_float cpg_d15[24];
extern cpg_float cpg_d16[24];
extern cpg_float cpg_d17[24];
extern cpg_float cpg_d18[24];
extern cpg_float cpg_d19[24];
extern cpg_float cpg_d20[24];
extern cpg_float cpg_d21[24];
extern cpg_float cpg_d22[24];
extern cpg_float cpg_d23[24];
extern cpg_float cpg_d24[24];
extern cpg_float cpg_d25[24];
extern cpg_float cpg_d26[24];
extern cpg_float cpg_d27[24];
extern cpg_float cpg_d28[24];
extern cpg_float cpg_d29[24];
extern cpg_float cpg_d30[24];
extern cpg_float cpg_d31[768];
extern cpg_float cpg_d32[128];
extern cpg_float cpg_d33[31];
extern cpg_float cpg_d34[31];
extern cpg_float cpg_d36[31];
extern cpg_float cpg_d37[8];
extern cpg_float cpg_d38[5];
extern cpg_float cpg_d39[3];
extern cpg_float cpg_d40[3];
extern cpg_float cpg_d54[4];
extern cpg_float cpg_d55[4];
extern cpg_float cpg_d56[32];
extern cpg_float cpg_d57[32];
extern cpg_float cpg_d58[96];

// Struct containing primal solution
extern CPG_Prim_t CPG_Prim;

// Struct containing dual solution
extern CPG_Dual_t CPG_Dual;

// Struct containing solver info
extern CPG_Info_t CPG_Info;

// Struct containing solution and info
extern CPG_Result_t CPG_Result;

// Struct containing solver settings
extern Canon_Settings_t Canon_Settings;

// QOCO array of SOC dimensions
extern cpg_int qoco_q[65];

// QOCO workspace
extern QOCOSolver* qoco_solver;

// QOCO exit flag
extern cpg_int qoco_flag;
