
/*
Auto-generated by CVXPYgen on April 04, 2026 at 20:44:39.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    double w_tr;
    double f_dt_last;
    std::array<double, 35> gf_dt_last;
    double f_ct_last;
    std::array<double, 28> A_ct_last;
    std::array<double, 12> B_ct_last;
    std::array<double, 12> C_ct_last;
    double f_comp_last;
    std::array<double, 35> gf_comp_last;
    std::array<double, 35> X_last;
    std::array<double, 28> f_bar;
    std::array<double, 196> A_bar;
    std::array<double, 84> B_bar;
    std::array<double, 84> C_bar;
    std::array<double, 15> U_last;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool w_tr;
    bool f_dt_last;
    bool gf_dt_last;
    bool f_ct_last;
    bool A_ct_last;
    bool B_ct_last;
    bool C_ct_last;
    bool f_comp_last;
    bool gf_comp_last;
    bool X_last;
    bool f_bar;
    bool A_bar;
    bool B_bar;
    bool C_bar;
    bool U_last;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 35> dx;
    std::array<double, 15> du;
    std::array<double, 28> nu;
    std::array<double, 35> X;
    std::array<double, 15> U;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 7> d0;
    std::array<double, 7> d1;
    std::array<double, 7> d2;
    std::array<double, 7> d3;
    std::array<double, 35> d4;
    std::array<double, 15> d5;
    double d6;
    std::array<double, 4> d7;
    std::array<double, 6> d8;
    std::array<double, 6> d9;
    std::array<double, 3> d10;
    std::array<double, 3> d11;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    int status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
