
/*
Auto-generated by CVXPYgen on April 04, 2026 at 20:44:39.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_w_tr(1.42206883329220201695);
  cpg_update_f_dt_last(-1.15010582328465971180);
  cpg_update_gf_dt_last(0, -0.41290051833404262105);
  cpg_update_f_ct_last(-0.47642194544604055118);
  cpg_update_A_ct_last(0, -0.32134455978624520966);
  cpg_update_B_ct_last(0, -0.01666439913539588188);
  cpg_update_C_ct_last(0, -0.81984664337714729943);
  cpg_update_f_comp_last(0.28690730071186482109);
  cpg_update_gf_comp_last(0, -0.56756312138104536569);
  cpg_update_X_last(0, 1.26208493372234120677);
  cpg_update_f_bar(0, 1.52906117421056841899);
  cpg_update_A_bar(0, 1.41970028418999438813);
  cpg_update_B_bar(0, 0.14699282047900166792);
  cpg_update_C_bar(0, 1.32034040046885126074);
  cpg_update_U_last(0, 0.44793846228699690792);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<35; i++) {
    printf("dx[%d] = %f\n", i, CPG_Result.prim->dx[i]);
  }
  for(i=0; i<15; i++) {
    printf("du[%d] = %f\n", i, CPG_Result.prim->du[i]);
  }
  for(i=0; i<28; i++) {
    printf("nu[%d] = %f\n", i, CPG_Result.prim->nu[i]);
  }
  for(i=0; i<35; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<15; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }

  // Print dual solution
  for(i=0; i<7; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<7; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<7; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<7; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<35; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<15; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  printf("d6 = %f\n", CPG_Result.dual->d6);
  for(i=0; i<4; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<6; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<6; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<3; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<3; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }

  return 0;

}
