
/*
Auto-generated by CVXPYgen on April 04, 2026 at 21:53:04.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    double w_tr;
    double f_ct_last;
    std::array<double, 744> A_ct_last;
    std::array<double, 124> B_ct_last;
    std::array<double, 124> C_ct_last;
    std::array<double, 31> S_ct_last;
    double f_comp_last;
    std::array<double, 768> gf_comp_last;
    std::array<double, 8> f_dt_last;
    std::array<double, 6144> gf_dt_last;
    std::array<double, 768> X_last;
    std::array<double, 744> f_bar;
    std::array<double, 17856> A_bar;
    std::array<double, 2976> B_bar;
    std::array<double, 2976> C_bar;
    std::array<double, 744> S_bar;
    std::array<double, 128> U_last;
    std::array<double, 31> S_last;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool w_tr;
    bool f_ct_last;
    bool A_ct_last;
    bool B_ct_last;
    bool C_ct_last;
    bool S_ct_last;
    bool f_comp_last;
    bool gf_comp_last;
    bool f_dt_last;
    bool gf_dt_last;
    bool X_last;
    bool f_bar;
    bool A_bar;
    bool B_bar;
    bool C_bar;
    bool S_bar;
    bool U_last;
    bool S_last;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 768> dx;
    std::array<double, 128> du;
    std::array<double, 31> ds;
    std::array<double, 744> nu;
    std::array<double, 31> S;
    std::array<double, 768> X;
    std::array<double, 128> U;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 24> d0;
    std::array<double, 24> d1;
    std::array<double, 24> d2;
    std::array<double, 24> d3;
    std::array<double, 24> d4;
    std::array<double, 24> d5;
    std::array<double, 24> d6;
    std::array<double, 24> d7;
    std::array<double, 24> d8;
    std::array<double, 24> d9;
    std::array<double, 24> d10;
    std::array<double, 24> d11;
    std::array<double, 24> d12;
    std::array<double, 24> d13;
    std::array<double, 24> d14;
    std::array<double, 24> d15;
    std::array<double, 24> d16;
    std::array<double, 24> d17;
    std::array<double, 24> d18;
    std::array<double, 24> d19;
    std::array<double, 24> d20;
    std::array<double, 24> d21;
    std::array<double, 24> d22;
    std::array<double, 24> d23;
    std::array<double, 24> d24;
    std::array<double, 24> d25;
    std::array<double, 24> d26;
    std::array<double, 24> d27;
    std::array<double, 24> d28;
    std::array<double, 24> d29;
    std::array<double, 24> d30;
    std::array<double, 768> d31;
    std::array<double, 128> d32;
    std::array<double, 31> d33;
    std::array<double, 31> d34;
    double d35;
    std::array<double, 31> d36;
    std::array<double, 8> d37;
    std::array<double, 5> d38;
    std::array<double, 3> d39;
    std::array<double, 3> d40;
    double d41;
    double d42;
    double d43;
    double d44;
    double d45;
    double d46;
    double d47;
    double d48;
    double d49;
    double d50;
    double d51;
    double d52;
    double d53;
    std::array<double, 4> d54;
    std::array<double, 4> d55;
    std::array<double, 32> d56;
    std::array<double, 32> d57;
    std::array<double, 96> d58;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    int status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
