
/*
Auto-generated by CVXPYgen on April 04, 2026 at 21:18:22.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_w_tr(0.21744966253374761744);
  cpg_update_f_ct_last(0.96571219074269221139);
  cpg_update_A_ct_last(0, -0.32689044477049800097);
  cpg_update_B_ct_last(0, 0.49314142971355384715);
  cpg_update_C_ct_last(0, 1.26784872038923523974);
  cpg_update_f_comp_last(-1.29372019491837275673);
  cpg_update_gf_comp_last(0, 0.27524342652696748290);
  cpg_update_f_dt_last(0, 0.16596916603368069842);
  cpg_update_gf_dt_last(0, -0.38861331523681713618);
  cpg_update_X_last(0, -2.18720691562283819920);
  cpg_update_f_bar(0, 0.37110348579343221953);
  cpg_update_A_bar(0, 0.50514450196531934800);
  cpg_update_B_bar(0, 0.98194289619511898604);
  cpg_update_C_bar(0, 0.39518962335963275789);
  cpg_update_U_last(0, 0.66614851980403433362);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<54; i++) {
    printf("dx[%d] = %f\n", i, CPG_Result.prim->dx[i]);
  }
  for(i=0; i<18; i++) {
    printf("du[%d] = %f\n", i, CPG_Result.prim->du[i]);
  }
  for(i=0; i<45; i++) {
    printf("nu[%d] = %f\n", i, CPG_Result.prim->nu[i]);
  }
  for(i=0; i<54; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<18; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }

  // Print dual solution
  for(i=0; i<9; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<9; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<9; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<9; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<9; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<54; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<18; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<6; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<6; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<2; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  printf("d10 = %f\n", CPG_Result.dual->d10);
  for(i=0; i<5; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<3; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<3; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }

  return 0;

}
