
/*
Auto-generated by CVXPYgen on April 04, 2026 at 21:18:22.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_w_tr(cpg_float val){
  cpg_params_vec[0] = val;
  Canon_Outdated.P = 1;
}

void cpg_update_f_ct_last(cpg_float val){
  cpg_params_vec[1] = val;
  Canon_Outdated.d = 1;
}

void cpg_update_A_ct_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_B_ct_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+47] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_C_ct_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+62] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_f_comp_last(cpg_float val){
  cpg_params_vec[77] = val;
  Canon_Outdated.d = 1;
}

void cpg_update_gf_comp_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+78] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_f_dt_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+132] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_gf_dt_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+134] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_X_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+242] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_f_bar(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+296] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_A_bar(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+341] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_bar(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+746] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_C_bar(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+881] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_U_last(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1016] = val;
  Canon_Outdated.b = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_P(){
  for(i=0; i<12; i++){
    Canon_Params.P->x[i] = 0;
    for(j=canon_P_map.p[i]; j<canon_P_map.p[i+1]; j++){
      Canon_Params.P->x[i] += canon_P_map.x[j]*cpg_params_vec[canon_P_map.i[j]];
    }
  }
}

void cpg_canonicalize_c(){
  for(i=0; i<248; i++){
    Canon_Params.c[i] = 0;
    for(j=canon_c_map.p[i]; j<canon_c_map.p[i+1]; j++){
      Canon_Params.c[i] += canon_c_map.x[j]*cpg_params_vec[canon_c_map.i[j]];
    }
  }
}

void cpg_canonicalize_d(){
  for(i=0; i<1; i++){
    Canon_Params.d = 0;
    for(j=canon_d_map.p[i]; j<canon_d_map.p[i+1]; j++){
      Canon_Params.d += canon_d_map.x[j]*cpg_params_vec[canon_d_map.i[j]];
    }
  }
}

void cpg_canonicalize_A(){
  for(i=0; i<930; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_b(){
  for(i=0; i<138; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

void cpg_canonicalize_G(){
  for(i=0; i<386; i++){
    Canon_Params.G->x[i] = 0;
    for(j=canon_G_map.p[i]; j<canon_G_map.p[i+1]; j++){
      Canon_Params.G->x[i] += canon_G_map.x[j]*cpg_params_vec[canon_G_map.i[j]];
    }
  }
}

void cpg_canonicalize_h(){
  for(i=0; i<183; i++){
    Canon_Params.h[i] = 0;
    for(j=canon_h_map.p[i]; j<canon_h_map.p[i+1]; j++){
      Canon_Params.h[i] += canon_h_map.x[j]*cpg_params_vec[canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.dx[0] = qoco_solver->sol->x[59];
  CPG_Prim.dx[1] = qoco_solver->sol->x[60];
  CPG_Prim.dx[2] = qoco_solver->sol->x[61];
  CPG_Prim.dx[3] = qoco_solver->sol->x[62];
  CPG_Prim.dx[4] = qoco_solver->sol->x[63];
  CPG_Prim.dx[5] = qoco_solver->sol->x[64];
  CPG_Prim.dx[6] = qoco_solver->sol->x[65];
  CPG_Prim.dx[7] = qoco_solver->sol->x[66];
  CPG_Prim.dx[8] = qoco_solver->sol->x[67];
  CPG_Prim.dx[9] = qoco_solver->sol->x[68];
  CPG_Prim.dx[10] = qoco_solver->sol->x[69];
  CPG_Prim.dx[11] = qoco_solver->sol->x[70];
  CPG_Prim.dx[12] = qoco_solver->sol->x[71];
  CPG_Prim.dx[13] = qoco_solver->sol->x[72];
  CPG_Prim.dx[14] = qoco_solver->sol->x[73];
  CPG_Prim.dx[15] = qoco_solver->sol->x[74];
  CPG_Prim.dx[16] = qoco_solver->sol->x[75];
  CPG_Prim.dx[17] = qoco_solver->sol->x[76];
  CPG_Prim.dx[18] = qoco_solver->sol->x[77];
  CPG_Prim.dx[19] = qoco_solver->sol->x[78];
  CPG_Prim.dx[20] = qoco_solver->sol->x[79];
  CPG_Prim.dx[21] = qoco_solver->sol->x[80];
  CPG_Prim.dx[22] = qoco_solver->sol->x[81];
  CPG_Prim.dx[23] = qoco_solver->sol->x[82];
  CPG_Prim.dx[24] = qoco_solver->sol->x[83];
  CPG_Prim.dx[25] = qoco_solver->sol->x[84];
  CPG_Prim.dx[26] = qoco_solver->sol->x[85];
  CPG_Prim.dx[27] = qoco_solver->sol->x[86];
  CPG_Prim.dx[28] = qoco_solver->sol->x[87];
  CPG_Prim.dx[29] = qoco_solver->sol->x[88];
  CPG_Prim.dx[30] = qoco_solver->sol->x[89];
  CPG_Prim.dx[31] = qoco_solver->sol->x[90];
  CPG_Prim.dx[32] = qoco_solver->sol->x[91];
  CPG_Prim.dx[33] = qoco_solver->sol->x[92];
  CPG_Prim.dx[34] = qoco_solver->sol->x[93];
  CPG_Prim.dx[35] = qoco_solver->sol->x[94];
  CPG_Prim.dx[36] = qoco_solver->sol->x[95];
  CPG_Prim.dx[37] = qoco_solver->sol->x[96];
  CPG_Prim.dx[38] = qoco_solver->sol->x[97];
  CPG_Prim.dx[39] = qoco_solver->sol->x[98];
  CPG_Prim.dx[40] = qoco_solver->sol->x[99];
  CPG_Prim.dx[41] = qoco_solver->sol->x[100];
  CPG_Prim.dx[42] = qoco_solver->sol->x[101];
  CPG_Prim.dx[43] = qoco_solver->sol->x[102];
  CPG_Prim.dx[44] = qoco_solver->sol->x[103];
  CPG_Prim.dx[45] = qoco_solver->sol->x[104];
  CPG_Prim.dx[46] = qoco_solver->sol->x[105];
  CPG_Prim.dx[47] = qoco_solver->sol->x[106];
  CPG_Prim.dx[48] = qoco_solver->sol->x[107];
  CPG_Prim.dx[49] = qoco_solver->sol->x[108];
  CPG_Prim.dx[50] = qoco_solver->sol->x[109];
  CPG_Prim.dx[51] = qoco_solver->sol->x[110];
  CPG_Prim.dx[52] = qoco_solver->sol->x[111];
  CPG_Prim.dx[53] = qoco_solver->sol->x[112];
  CPG_Prim.du[0] = qoco_solver->sol->x[113];
  CPG_Prim.du[1] = qoco_solver->sol->x[114];
  CPG_Prim.du[2] = qoco_solver->sol->x[115];
  CPG_Prim.du[3] = qoco_solver->sol->x[116];
  CPG_Prim.du[4] = qoco_solver->sol->x[117];
  CPG_Prim.du[5] = qoco_solver->sol->x[118];
  CPG_Prim.du[6] = qoco_solver->sol->x[119];
  CPG_Prim.du[7] = qoco_solver->sol->x[120];
  CPG_Prim.du[8] = qoco_solver->sol->x[121];
  CPG_Prim.du[9] = qoco_solver->sol->x[122];
  CPG_Prim.du[10] = qoco_solver->sol->x[123];
  CPG_Prim.du[11] = qoco_solver->sol->x[124];
  CPG_Prim.du[12] = qoco_solver->sol->x[125];
  CPG_Prim.du[13] = qoco_solver->sol->x[126];
  CPG_Prim.du[14] = qoco_solver->sol->x[127];
  CPG_Prim.du[15] = qoco_solver->sol->x[128];
  CPG_Prim.du[16] = qoco_solver->sol->x[129];
  CPG_Prim.du[17] = qoco_solver->sol->x[130];
  CPG_Prim.nu[0] = qoco_solver->sol->x[131];
  CPG_Prim.nu[1] = qoco_solver->sol->x[132];
  CPG_Prim.nu[2] = qoco_solver->sol->x[133];
  CPG_Prim.nu[3] = qoco_solver->sol->x[134];
  CPG_Prim.nu[4] = qoco_solver->sol->x[135];
  CPG_Prim.nu[5] = qoco_solver->sol->x[136];
  CPG_Prim.nu[6] = qoco_solver->sol->x[137];
  CPG_Prim.nu[7] = qoco_solver->sol->x[138];
  CPG_Prim.nu[8] = qoco_solver->sol->x[139];
  CPG_Prim.nu[9] = qoco_solver->sol->x[140];
  CPG_Prim.nu[10] = qoco_solver->sol->x[141];
  CPG_Prim.nu[11] = qoco_solver->sol->x[142];
  CPG_Prim.nu[12] = qoco_solver->sol->x[143];
  CPG_Prim.nu[13] = qoco_solver->sol->x[144];
  CPG_Prim.nu[14] = qoco_solver->sol->x[145];
  CPG_Prim.nu[15] = qoco_solver->sol->x[146];
  CPG_Prim.nu[16] = qoco_solver->sol->x[147];
  CPG_Prim.nu[17] = qoco_solver->sol->x[148];
  CPG_Prim.nu[18] = qoco_solver->sol->x[149];
  CPG_Prim.nu[19] = qoco_solver->sol->x[150];
  CPG_Prim.nu[20] = qoco_solver->sol->x[151];
  CPG_Prim.nu[21] = qoco_solver->sol->x[152];
  CPG_Prim.nu[22] = qoco_solver->sol->x[153];
  CPG_Prim.nu[23] = qoco_solver->sol->x[154];
  CPG_Prim.nu[24] = qoco_solver->sol->x[155];
  CPG_Prim.nu[25] = qoco_solver->sol->x[156];
  CPG_Prim.nu[26] = qoco_solver->sol->x[157];
  CPG_Prim.nu[27] = qoco_solver->sol->x[158];
  CPG_Prim.nu[28] = qoco_solver->sol->x[159];
  CPG_Prim.nu[29] = qoco_solver->sol->x[160];
  CPG_Prim.nu[30] = qoco_solver->sol->x[161];
  CPG_Prim.nu[31] = qoco_solver->sol->x[162];
  CPG_Prim.nu[32] = qoco_solver->sol->x[163];
  CPG_Prim.nu[33] = qoco_solver->sol->x[164];
  CPG_Prim.nu[34] = qoco_solver->sol->x[165];
  CPG_Prim.nu[35] = qoco_solver->sol->x[166];
  CPG_Prim.nu[36] = qoco_solver->sol->x[167];
  CPG_Prim.nu[37] = qoco_solver->sol->x[168];
  CPG_Prim.nu[38] = qoco_solver->sol->x[169];
  CPG_Prim.nu[39] = qoco_solver->sol->x[170];
  CPG_Prim.nu[40] = qoco_solver->sol->x[171];
  CPG_Prim.nu[41] = qoco_solver->sol->x[172];
  CPG_Prim.nu[42] = qoco_solver->sol->x[173];
  CPG_Prim.nu[43] = qoco_solver->sol->x[174];
  CPG_Prim.nu[44] = qoco_solver->sol->x[175];
  CPG_Prim.X[0] = qoco_solver->sol->x[176];
  CPG_Prim.X[1] = qoco_solver->sol->x[177];
  CPG_Prim.X[2] = qoco_solver->sol->x[178];
  CPG_Prim.X[3] = qoco_solver->sol->x[179];
  CPG_Prim.X[4] = qoco_solver->sol->x[180];
  CPG_Prim.X[5] = qoco_solver->sol->x[181];
  CPG_Prim.X[6] = qoco_solver->sol->x[182];
  CPG_Prim.X[7] = qoco_solver->sol->x[183];
  CPG_Prim.X[8] = qoco_solver->sol->x[184];
  CPG_Prim.X[9] = qoco_solver->sol->x[185];
  CPG_Prim.X[10] = qoco_solver->sol->x[186];
  CPG_Prim.X[11] = qoco_solver->sol->x[187];
  CPG_Prim.X[12] = qoco_solver->sol->x[188];
  CPG_Prim.X[13] = qoco_solver->sol->x[189];
  CPG_Prim.X[14] = qoco_solver->sol->x[190];
  CPG_Prim.X[15] = qoco_solver->sol->x[191];
  CPG_Prim.X[16] = qoco_solver->sol->x[192];
  CPG_Prim.X[17] = qoco_solver->sol->x[193];
  CPG_Prim.X[18] = qoco_solver->sol->x[194];
  CPG_Prim.X[19] = qoco_solver->sol->x[195];
  CPG_Prim.X[20] = qoco_solver->sol->x[196];
  CPG_Prim.X[21] = qoco_solver->sol->x[197];
  CPG_Prim.X[22] = qoco_solver->sol->x[198];
  CPG_Prim.X[23] = qoco_solver->sol->x[199];
  CPG_Prim.X[24] = qoco_solver->sol->x[200];
  CPG_Prim.X[25] = qoco_solver->sol->x[201];
  CPG_Prim.X[26] = qoco_solver->sol->x[202];
  CPG_Prim.X[27] = qoco_solver->sol->x[203];
  CPG_Prim.X[28] = qoco_solver->sol->x[204];
  CPG_Prim.X[29] = qoco_solver->sol->x[205];
  CPG_Prim.X[30] = qoco_solver->sol->x[206];
  CPG_Prim.X[31] = qoco_solver->sol->x[207];
  CPG_Prim.X[32] = qoco_solver->sol->x[208];
  CPG_Prim.X[33] = qoco_solver->sol->x[209];
  CPG_Prim.X[34] = qoco_solver->sol->x[210];
  CPG_Prim.X[35] = qoco_solver->sol->x[211];
  CPG_Prim.X[36] = qoco_solver->sol->x[212];
  CPG_Prim.X[37] = qoco_solver->sol->x[213];
  CPG_Prim.X[38] = qoco_solver->sol->x[214];
  CPG_Prim.X[39] = qoco_solver->sol->x[215];
  CPG_Prim.X[40] = qoco_solver->sol->x[216];
  CPG_Prim.X[41] = qoco_solver->sol->x[217];
  CPG_Prim.X[42] = qoco_solver->sol->x[218];
  CPG_Prim.X[43] = qoco_solver->sol->x[219];
  CPG_Prim.X[44] = qoco_solver->sol->x[220];
  CPG_Prim.X[45] = qoco_solver->sol->x[221];
  CPG_Prim.X[46] = qoco_solver->sol->x[222];
  CPG_Prim.X[47] = qoco_solver->sol->x[223];
  CPG_Prim.X[48] = qoco_solver->sol->x[224];
  CPG_Prim.X[49] = qoco_solver->sol->x[225];
  CPG_Prim.X[50] = qoco_solver->sol->x[226];
  CPG_Prim.X[51] = qoco_solver->sol->x[227];
  CPG_Prim.X[52] = qoco_solver->sol->x[228];
  CPG_Prim.X[53] = qoco_solver->sol->x[229];
  CPG_Prim.U[0] = qoco_solver->sol->x[230];
  CPG_Prim.U[1] = qoco_solver->sol->x[231];
  CPG_Prim.U[2] = qoco_solver->sol->x[232];
  CPG_Prim.U[3] = qoco_solver->sol->x[233];
  CPG_Prim.U[4] = qoco_solver->sol->x[234];
  CPG_Prim.U[5] = qoco_solver->sol->x[235];
  CPG_Prim.U[6] = qoco_solver->sol->x[236];
  CPG_Prim.U[7] = qoco_solver->sol->x[237];
  CPG_Prim.U[8] = qoco_solver->sol->x[238];
  CPG_Prim.U[9] = qoco_solver->sol->x[239];
  CPG_Prim.U[10] = qoco_solver->sol->x[240];
  CPG_Prim.U[11] = qoco_solver->sol->x[241];
  CPG_Prim.U[12] = qoco_solver->sol->x[242];
  CPG_Prim.U[13] = qoco_solver->sol->x[243];
  CPG_Prim.U[14] = qoco_solver->sol->x[244];
  CPG_Prim.U[15] = qoco_solver->sol->x[245];
  CPG_Prim.U[16] = qoco_solver->sol->x[246];
  CPG_Prim.U[17] = qoco_solver->sol->x[247];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = qoco_solver->sol->y[0];
  CPG_Dual.d0[1] = qoco_solver->sol->y[1];
  CPG_Dual.d0[2] = qoco_solver->sol->y[2];
  CPG_Dual.d0[3] = qoco_solver->sol->y[3];
  CPG_Dual.d0[4] = qoco_solver->sol->y[4];
  CPG_Dual.d0[5] = qoco_solver->sol->y[5];
  CPG_Dual.d0[6] = qoco_solver->sol->y[6];
  CPG_Dual.d0[7] = qoco_solver->sol->y[7];
  CPG_Dual.d0[8] = qoco_solver->sol->y[8];
  CPG_Dual.d1[0] = qoco_solver->sol->y[9];
  CPG_Dual.d1[1] = qoco_solver->sol->y[10];
  CPG_Dual.d1[2] = qoco_solver->sol->y[11];
  CPG_Dual.d1[3] = qoco_solver->sol->y[12];
  CPG_Dual.d1[4] = qoco_solver->sol->y[13];
  CPG_Dual.d1[5] = qoco_solver->sol->y[14];
  CPG_Dual.d1[6] = qoco_solver->sol->y[15];
  CPG_Dual.d1[7] = qoco_solver->sol->y[16];
  CPG_Dual.d1[8] = qoco_solver->sol->y[17];
  CPG_Dual.d2[0] = qoco_solver->sol->y[18];
  CPG_Dual.d2[1] = qoco_solver->sol->y[19];
  CPG_Dual.d2[2] = qoco_solver->sol->y[20];
  CPG_Dual.d2[3] = qoco_solver->sol->y[21];
  CPG_Dual.d2[4] = qoco_solver->sol->y[22];
  CPG_Dual.d2[5] = qoco_solver->sol->y[23];
  CPG_Dual.d2[6] = qoco_solver->sol->y[24];
  CPG_Dual.d2[7] = qoco_solver->sol->y[25];
  CPG_Dual.d2[8] = qoco_solver->sol->y[26];
  CPG_Dual.d3[0] = qoco_solver->sol->y[27];
  CPG_Dual.d3[1] = qoco_solver->sol->y[28];
  CPG_Dual.d3[2] = qoco_solver->sol->y[29];
  CPG_Dual.d3[3] = qoco_solver->sol->y[30];
  CPG_Dual.d3[4] = qoco_solver->sol->y[31];
  CPG_Dual.d3[5] = qoco_solver->sol->y[32];
  CPG_Dual.d3[6] = qoco_solver->sol->y[33];
  CPG_Dual.d3[7] = qoco_solver->sol->y[34];
  CPG_Dual.d3[8] = qoco_solver->sol->y[35];
  CPG_Dual.d4[0] = qoco_solver->sol->y[36];
  CPG_Dual.d4[1] = qoco_solver->sol->y[37];
  CPG_Dual.d4[2] = qoco_solver->sol->y[38];
  CPG_Dual.d4[3] = qoco_solver->sol->y[39];
  CPG_Dual.d4[4] = qoco_solver->sol->y[40];
  CPG_Dual.d4[5] = qoco_solver->sol->y[41];
  CPG_Dual.d4[6] = qoco_solver->sol->y[42];
  CPG_Dual.d4[7] = qoco_solver->sol->y[43];
  CPG_Dual.d4[8] = qoco_solver->sol->y[44];
  CPG_Dual.d5[0] = qoco_solver->sol->y[45];
  CPG_Dual.d5[1] = qoco_solver->sol->y[46];
  CPG_Dual.d5[2] = qoco_solver->sol->y[47];
  CPG_Dual.d5[3] = qoco_solver->sol->y[48];
  CPG_Dual.d5[4] = qoco_solver->sol->y[49];
  CPG_Dual.d5[5] = qoco_solver->sol->y[50];
  CPG_Dual.d5[6] = qoco_solver->sol->y[51];
  CPG_Dual.d5[7] = qoco_solver->sol->y[52];
  CPG_Dual.d5[8] = qoco_solver->sol->y[53];
  CPG_Dual.d5[9] = qoco_solver->sol->y[54];
  CPG_Dual.d5[10] = qoco_solver->sol->y[55];
  CPG_Dual.d5[11] = qoco_solver->sol->y[56];
  CPG_Dual.d5[12] = qoco_solver->sol->y[57];
  CPG_Dual.d5[13] = qoco_solver->sol->y[58];
  CPG_Dual.d5[14] = qoco_solver->sol->y[59];
  CPG_Dual.d5[15] = qoco_solver->sol->y[60];
  CPG_Dual.d5[16] = qoco_solver->sol->y[61];
  CPG_Dual.d5[17] = qoco_solver->sol->y[62];
  CPG_Dual.d5[18] = qoco_solver->sol->y[63];
  CPG_Dual.d5[19] = qoco_solver->sol->y[64];
  CPG_Dual.d5[20] = qoco_solver->sol->y[65];
  CPG_Dual.d5[21] = qoco_solver->sol->y[66];
  CPG_Dual.d5[22] = qoco_solver->sol->y[67];
  CPG_Dual.d5[23] = qoco_solver->sol->y[68];
  CPG_Dual.d5[24] = qoco_solver->sol->y[69];
  CPG_Dual.d5[25] = qoco_solver->sol->y[70];
  CPG_Dual.d5[26] = qoco_solver->sol->y[71];
  CPG_Dual.d5[27] = qoco_solver->sol->y[72];
  CPG_Dual.d5[28] = qoco_solver->sol->y[73];
  CPG_Dual.d5[29] = qoco_solver->sol->y[74];
  CPG_Dual.d5[30] = qoco_solver->sol->y[75];
  CPG_Dual.d5[31] = qoco_solver->sol->y[76];
  CPG_Dual.d5[32] = qoco_solver->sol->y[77];
  CPG_Dual.d5[33] = qoco_solver->sol->y[78];
  CPG_Dual.d5[34] = qoco_solver->sol->y[79];
  CPG_Dual.d5[35] = qoco_solver->sol->y[80];
  CPG_Dual.d5[36] = qoco_solver->sol->y[81];
  CPG_Dual.d5[37] = qoco_solver->sol->y[82];
  CPG_Dual.d5[38] = qoco_solver->sol->y[83];
  CPG_Dual.d5[39] = qoco_solver->sol->y[84];
  CPG_Dual.d5[40] = qoco_solver->sol->y[85];
  CPG_Dual.d5[41] = qoco_solver->sol->y[86];
  CPG_Dual.d5[42] = qoco_solver->sol->y[87];
  CPG_Dual.d5[43] = qoco_solver->sol->y[88];
  CPG_Dual.d5[44] = qoco_solver->sol->y[89];
  CPG_Dual.d5[45] = qoco_solver->sol->y[90];
  CPG_Dual.d5[46] = qoco_solver->sol->y[91];
  CPG_Dual.d5[47] = qoco_solver->sol->y[92];
  CPG_Dual.d5[48] = qoco_solver->sol->y[93];
  CPG_Dual.d5[49] = qoco_solver->sol->y[94];
  CPG_Dual.d5[50] = qoco_solver->sol->y[95];
  CPG_Dual.d5[51] = qoco_solver->sol->y[96];
  CPG_Dual.d5[52] = qoco_solver->sol->y[97];
  CPG_Dual.d5[53] = qoco_solver->sol->y[98];
  CPG_Dual.d6[0] = qoco_solver->sol->y[99];
  CPG_Dual.d6[1] = qoco_solver->sol->y[100];
  CPG_Dual.d6[2] = qoco_solver->sol->y[101];
  CPG_Dual.d6[3] = qoco_solver->sol->y[102];
  CPG_Dual.d6[4] = qoco_solver->sol->y[103];
  CPG_Dual.d6[5] = qoco_solver->sol->y[104];
  CPG_Dual.d6[6] = qoco_solver->sol->y[105];
  CPG_Dual.d6[7] = qoco_solver->sol->y[106];
  CPG_Dual.d6[8] = qoco_solver->sol->y[107];
  CPG_Dual.d6[9] = qoco_solver->sol->y[108];
  CPG_Dual.d6[10] = qoco_solver->sol->y[109];
  CPG_Dual.d6[11] = qoco_solver->sol->y[110];
  CPG_Dual.d6[12] = qoco_solver->sol->y[111];
  CPG_Dual.d6[13] = qoco_solver->sol->y[112];
  CPG_Dual.d6[14] = qoco_solver->sol->y[113];
  CPG_Dual.d6[15] = qoco_solver->sol->y[114];
  CPG_Dual.d6[16] = qoco_solver->sol->y[115];
  CPG_Dual.d6[17] = qoco_solver->sol->y[116];
  CPG_Dual.d7[0] = qoco_solver->sol->y[117];
  CPG_Dual.d7[1] = qoco_solver->sol->y[118];
  CPG_Dual.d7[2] = qoco_solver->sol->y[119];
  CPG_Dual.d7[3] = qoco_solver->sol->y[120];
  CPG_Dual.d7[4] = qoco_solver->sol->y[121];
  CPG_Dual.d7[5] = qoco_solver->sol->y[122];
  CPG_Dual.d8[0] = qoco_solver->sol->y[123];
  CPG_Dual.d8[1] = qoco_solver->sol->y[124];
  CPG_Dual.d8[2] = qoco_solver->sol->y[125];
  CPG_Dual.d8[3] = qoco_solver->sol->y[126];
  CPG_Dual.d8[4] = qoco_solver->sol->y[127];
  CPG_Dual.d8[5] = qoco_solver->sol->y[128];
  CPG_Dual.d9[0] = qoco_solver->sol->y[129];
  CPG_Dual.d9[1] = qoco_solver->sol->y[130];
  CPG_Dual.d10 = qoco_solver->sol->y[131];
  CPG_Dual.d11[0] = qoco_solver->sol->z[94];
  CPG_Dual.d11[1] = qoco_solver->sol->z[95];
  CPG_Dual.d11[2] = qoco_solver->sol->z[96];
  CPG_Dual.d11[3] = qoco_solver->sol->z[97];
  CPG_Dual.d11[4] = qoco_solver->sol->z[98];
  CPG_Dual.d12[0] = qoco_solver->sol->y[132];
  CPG_Dual.d12[1] = qoco_solver->sol->y[133];
  CPG_Dual.d12[2] = qoco_solver->sol->y[134];
  CPG_Dual.d13[0] = qoco_solver->sol->y[135];
  CPG_Dual.d13[1] = qoco_solver->sol->y[136];
  CPG_Dual.d13[2] = qoco_solver->sol->y[137];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (qoco_solver->sol->obj + Canon_Params.d);
  CPG_Info.iter = qoco_solver->sol->iters;
  CPG_Info.status = qoco_solver->sol->status;
  CPG_Info.pri_res = qoco_solver->sol->pres;
  CPG_Info.dua_res = qoco_solver->sol->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_P(){
  for (i=0; i<12; i++){
    Canon_Params_conditioning.P->x[i] = Canon_Params.P->x[i];
  }
}

void cpg_copy_c(){
  for (i=0; i<248; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
  for (i=0; i<930; i++){
    Canon_Params_conditioning.A->x[i] = Canon_Params.A->x[i];
  }
}

void cpg_copy_b(){
  for (i=0; i<138; i++){
    Canon_Params_conditioning.b[i] = Canon_Params.b[i];
  }
}

void cpg_copy_G(){
  for (i=0; i<386; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<183; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_P();
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.P) {
    cpg_canonicalize_P();
  }
  if (Canon_Outdated.c) {
    cpg_canonicalize_c();
  }
  if (Canon_Outdated.d) {
    cpg_canonicalize_d();
  }
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (Canon_Outdated.G) {
    cpg_canonicalize_G();
  }
  if (Canon_Outdated.h) {
    cpg_canonicalize_h();
  }
  if (!qoco_solver ) {
    cpg_copy_all();
   QOCOCscMatrix* P = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* A = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* G = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   qoco_set_csc(P, 248, 248, Canon_Params.P->nnz, Canon_Params.P->x, Canon_Params.P->p, Canon_Params.P->i);
   qoco_set_csc(A, 138, 248, Canon_Params.A->nnz, Canon_Params.A->x, Canon_Params.A->p, Canon_Params.A->i);
   qoco_set_csc(G, 183, 248, Canon_Params.G->nnz, Canon_Params.G->x, Canon_Params.G->p, Canon_Params.G->i);
   QOCOSettings* qoco_settings = (QOCOSettings*)malloc(sizeof(QOCOSettings));
   set_default_settings(qoco_settings);
   qoco_solver = (QOCOSolver*)malloc(sizeof(QOCOSolver));
   qoco_setup(qoco_solver, 248, 183, 138, P, Canon_Params.c, A, Canon_Params.b, G, Canon_Params.h, 99, 12, (int *) &qoco_q, qoco_settings);
  }
  if (Canon_Outdated.h) {
    update_vector_data(qoco_solver, NULL, NULL, Canon_Params.h);
  }
  if (Canon_Outdated.G) {
    update_matrix_data(qoco_solver, NULL, NULL, Canon_Params.G->x);
  }
  if (Canon_Outdated.P) {
    update_matrix_data(qoco_solver, Canon_Params.P->x, NULL, NULL);
  }
  if (Canon_Outdated.b) {
    update_vector_data(qoco_solver, NULL, Canon_Params.b, NULL);
  }
  if (Canon_Outdated.c) {
    update_vector_data(qoco_solver, Canon_Params.c, NULL, NULL);
  }
  if (Canon_Outdated.A) {
    update_matrix_data(qoco_solver, NULL, Canon_Params.A->x, NULL);
  }
  qoco_solver->settings->max_iters = Canon_Settings.max_iters;
  qoco_solver->settings->bisect_iters = Canon_Settings.bisect_iters;
  qoco_solver->settings->ruiz_iters = Canon_Settings.ruiz_iters;
  qoco_solver->settings->iter_ref_iters = Canon_Settings.iter_ref_iters;
  qoco_solver->settings->kkt_static_reg = Canon_Settings.kkt_static_reg;
  qoco_solver->settings->kkt_dynamic_reg = Canon_Settings.kkt_dynamic_reg;
  qoco_solver->settings->abstol = Canon_Settings.abstol;
  qoco_solver->settings->reltol = Canon_Settings.reltol;
  qoco_solver->settings->abstol_inacc = Canon_Settings.abstol_inacc;
  qoco_solver->settings->reltol_inacc = Canon_Settings.reltol_inacc;
  qoco_solver->settings->verbose = Canon_Settings.verbose;
  // Solve with QOCO
  qoco_solve(qoco_solver);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.P = 0;
  Canon_Outdated.c = 0;
  Canon_Outdated.d = 0;
  Canon_Outdated.A = 0;
  Canon_Outdated.b = 0;
  Canon_Outdated.G = 0;
  Canon_Outdated.h = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.max_iters = 200;
  Canon_Settings.bisect_iters = 5;
  Canon_Settings.ruiz_iters = 0;
  Canon_Settings.iter_ref_iters = 1;
  Canon_Settings.kkt_static_reg = 1e-8;
  Canon_Settings.kkt_dynamic_reg = 1e-8;
  Canon_Settings.abstol = 1e-7;
  Canon_Settings.reltol = 1e-7;
  Canon_Settings.abstol_inacc = 1e-5;
  Canon_Settings.reltol_inacc = 1e-5;
  Canon_Settings.verbose = 0;
}

void cpg_set_solver_max_iters(cpg_int max_iters_new){
  Canon_Settings.max_iters = max_iters_new;
}

void cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  Canon_Settings.bisect_iters = bisect_iters_new;
}

void cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  Canon_Settings.ruiz_iters = ruiz_iters_new;
}

void cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  Canon_Settings.iter_ref_iters = iter_ref_iters_new;
}

void cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  Canon_Settings.kkt_static_reg = kkt_static_reg_new;
}

void cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  Canon_Settings.kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_verbose(cpg_int verbose_new){
  Canon_Settings.verbose = verbose_new;
}
