
/*
Auto-generated by CVXPYgen on April 04, 2026 at 22:01:48.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_w_tr(0.00000000000000000000);
  cpg_update_f_ct_last(-0.59774294649253234546);
  cpg_update_A_ct_last(0, 0.09218643639478174556);
  cpg_update_B_ct_last(0, -0.66763850582197092898);
  cpg_update_C_ct_last(0, -1.63971386032343624528);
  cpg_update_f_comp_last(0.78549882060781150983);
  cpg_update_gf_comp_last(0, 1.11867199674184392144);
  cpg_update_f_dt_last(0.91839938274954469044);
  cpg_update_gf_dt_last(0, -0.02279842514401339559);
  cpg_update_X_last(0, 0.61282516022216171336);
  cpg_update_f_bar(0, 0.23828343240321181451);
  cpg_update_A_bar(0, -0.05273940207285737758);
  cpg_update_B_bar(0, 0.74538294447640451867);
  cpg_update_C_bar(0, -1.12200297941270199509);
  cpg_update_U_last(0, -0.83832816301041945817);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<54; i++) {
    printf("dx[%d] = %f\n", i, CPG_Result.prim->dx[i]);
  }
  for(i=0; i<18; i++) {
    printf("du[%d] = %f\n", i, CPG_Result.prim->du[i]);
  }
  for(i=0; i<45; i++) {
    printf("nu[%d] = %f\n", i, CPG_Result.prim->nu[i]);
  }
  for(i=0; i<54; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<18; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }

  // Print dual solution
  for(i=0; i<9; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<9; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<9; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<9; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<9; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<54; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<18; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<6; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<6; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  printf("d9 = %f\n", CPG_Result.dual->d9);
  printf("d10 = %f\n", CPG_Result.dual->d10);
  printf("d11 = %f\n", CPG_Result.dual->d11);
  for(i=0; i<5; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<3; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<3; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }

  return 0;

}
