
/*
Auto-generated by CVXPYgen on April 04, 2026 at 21:17:28.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_w_tr(0.00000000000000000000);
  cpg_update_f_ct_last(-0.49308578027526644982);
  cpg_update_A_ct_last(0, -1.91464780846978843698);
  cpg_update_B_ct_last(0, -0.62358609847181256658);
  cpg_update_C_ct_last(0, -0.59764323678597408573);
  cpg_update_f_comp_last(-0.99950288096567363461);
  cpg_update_gf_comp_last(0, -1.08096860547664697094);
  cpg_update_f_dt_last(0, -0.97654084404840824085);
  cpg_update_gf_dt_last(0, 0.80112091730257961597);
  cpg_update_X_last(0, 0.80348559075532077767);
  cpg_update_f_bar(0, -0.34530508078966121177);
  cpg_update_A_bar(0, -0.05273873404322877712);
  cpg_update_B_bar(0, -0.47135249240037357943);
  cpg_update_C_bar(0, 0.13544169702774122577);
  cpg_update_U_last(0, -0.19956224535599148551);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<91; i++) {
    printf("dx[%d] = %f\n", i, CPG_Result.prim->dx[i]);
  }
  for(i=0; i<21; i++) {
    printf("du[%d] = %f\n", i, CPG_Result.prim->du[i]);
  }
  for(i=0; i<78; i++) {
    printf("nu[%d] = %f\n", i, CPG_Result.prim->nu[i]);
  }
  for(i=0; i<91; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<21; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }

  // Print dual solution
  for(i=0; i<13; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<13; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<13; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<13; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<13; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<13; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<91; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<21; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<6; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<6; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  printf("d10 = %f\n", CPG_Result.dual->d10);
  printf("d11 = %f\n", CPG_Result.dual->d11);
  printf("d12 = %f\n", CPG_Result.dual->d12);
  printf("d13 = %f\n", CPG_Result.dual->d13);
  printf("d14 = %f\n", CPG_Result.dual->d14);
  printf("d15 = %f\n", CPG_Result.dual->d15);
  printf("d16 = %f\n", CPG_Result.dual->d16);
  for(i=0; i<6; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<3; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<3; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }

  return 0;

}
